### ISSUE TITLE
MyAnimeList API

### ISSUE THREAD

**Issue by farrandi** [Personal-MLE-Projects/anirec#1]
We need to figure out:
- How to use the MAL API
- What data does that get
- Do we need to anonymize the data?
- What other data do we need to make the utility matrix?

[Add more questions if we need to]

**Comment by AReyH** [comment]
>>> How to use the MAL API: Here is a sample code that the author shared on gitlab: 
https://gitlab.com/-/snippets/2039434

>> What data does that get:
* retrieve some information about specific anime or manga;
* access general and seasonal rankings;
* update a user's anime/manga list;
* read forum topics;
* get some information about the authenticated user.

>>> Do we need to anonymize the data: 
Yes, most likely, especially if we are gonna scrape the data.

>>> What other data do we need to make the utility matrix: 
We are gonna be able to get the scores, the rankings, and if the user is currently watching the anime.



Here is the source from where we can get info about the API.


Also, we already have an account to use the API, but we may not be able to get user rankings with it.
